In [1]:
import pandas as pd
import os
import math
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
import seaborn as sns
import mglearn

df = pd.read_csv('BTCUSD_2021.csv')

df['date'] = pd.to_datetime(df['date'], unit='s')

df.head()

date       low      high      open     close    volume
0 2021-01-01 00:00:00  28965.01  29015.49  28978.66  29015.49  1.030971
1 2021-01-01 00:01:00  29012.96  29050.52  29014.55  29049.52  2.104348
2 2021-01-01 00:02:00  29040.69  29050.52  29049.05  29040.69  0.141871
3 2021-01-01 00:03:00  29021.26  29041.70  29040.45  29040.57  0.039191
4 2021-01-01 00:04:00  29020.39  29040.57  29034.12  29031.48  1.927880

In [2]:
df.close = pd.Categorical(df.close)
df.close = df.close.cat.codes

In [3]:
from sklearn.model_selection import train_test_split 
from sklearn.neighbors import KNeighborsClassifier

features = df[["low","high","open","volume"]]

target = df.close

X = features
y = target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

knn = KNeighborsClassifier(n_neighbors=2)
knn.fit(X_train, y_train)
knn.score(X_train, y_train)
knn.score(X_test, y_test)

0.0024915650142745913

In [4]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, recall_score, precision_score, fbeta_score, classification_report

pred = knn.predict(X_test)

print("confusion matrix:")
print(confusion_matrix(y_test, pred))

print("accuracy: %0.3f" % accuracy_score(y_test, pred))

confusion matrix:
[[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
accuracy: 0.002
